### ISSUE TITLE
bottom status bar interferes with last line of text

### ISSUE THREAD

**Issue by jlgerber** [Zeioth/atom-visual-studio-code-ui#1]
I notice with this theme ( as much as I like it ) that the larger blue notification bar at the bottom interferes with displaying the last line of text for sufficiently large documents

**Comment by Zeioth** [comment]
I've found a thread about [this](https://discuss.atom.io/t/rearrange-status-bar-to-the-bottom-panel/18597/7) problem. It looks like right now, due to the CSS structure of atom, it's not possible to set 100% width in the status bar without running into this bug. They are working on it.

Meanwhile you can paste this into your styles.less, the status bar will be smaller but it will fix this issue.

``` css
.status-bar {
  position: relative;
}
```

**Comment by Zeioth** [comment]
The new version includes this solution by default.
